### ISSUE TITLE
[1.21.1] Fabric issue

### ISSUE THREAD

**Issue by Fenius64** [MC-U-Team/Music-Player#1210]
### Bug description and reproduction steps

Launch Fabric 1.21.1 With The Mod

please update the mod to work with 1.21.1, fabric throws a "incompatible version" everytime i boot it with 1.21.1, thjnk you

### Log files and Screenshots

20:21:08] [main/INFO]: Loading Minecraft 1.21.1 with Fabric Loader 0.16.3
[20:21:08] [ForkJoinPool-1-worker-3/WARN]: Mod cpm uses the version 0.6.17d which isn't compatible with Loader's extended semantic version format (Could not parse version number component '17d'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[20:21:08] [main/WARN]: Mod resolution failed
[20:21:08] [main/INFO]: Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED musicplayer 2.7.1.294 {depends minecraft @ [1.21]}, ROOT_FORCELOAD_SINGLE musicplayer 2.7.1.294]
[20:21:08] [main/INFO]: Reason: [HARD_DEP musicplayer 2.7.1.294 {depends minecraft @ [1.21]}, HARD_DEP uteamcore 5.6.0.318 {depends minecraft @ [1.21]}]
[20:21:08] [main/INFO]: Fix: add [], remove [], replace [[musicplayer 2.7.1.294] -> add:musicplayer 1 ([(-∞,∞)]), [uteamcore 5.6.0.318] -> add:uteamcore 5.6.0.317 ([(-∞,∞)])]
[20:21:08] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Music Player' (musicplayer) 2.7.1.294 with any version that is compatible with:
		 - uteamcore, any version
		 - minecraft 1.21.1
	 - Replace mod 'U Team Core' (uteamcore) 5.6.0.318 with any version that is compatible with:
		 - minecraft 1.21.1
More details:
	 - Mod 'Music Player' (musicplayer) 2.7.1.294 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	 - Mod 'U Team Core' (uteamcore) 5.6.0.318 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.3.jar:?]

### Used minecraft version

1.21.x

### Used forge or fabric version

Fabric 0.16.3

### Used mod version

2.7.1.294

**Comment by Fenius64** [comment]
![image](https://github.com/user-attachments/assets/7a0fe74c-f3c9-4ea2-a9cc-bd7bd1230a94)
this is what it says when i try to, please update it to the latest.

**Comment by HyCraftHD** [comment]
You used the 1.21 version with is not compatible with 1.21.1.
A 1.21.1 version does not exist.
