### ISSUE TITLE
Tracks skipping  [MC-Version] 1.8 - 1.21 (It happens on every version I've played it on)

### ISSUE THREAD

**Issue by VulDovahkiin** [MC-U-Team/Music-Player#1243]
### Bug description and reproduction steps

I don't know if it's a bug necessarily, but it's still REALLY annoying. 

So I have this habit of having a BUNCH of random tracks, and then skipping through them to fit what mood I'm in at that moment.
Now for some reason(And I hope it's a bug and not a feature, because otherwise it's a stupid feature) it's just skipping tracks on it's own.

I've tried deleting my tracks, deleting the config, deleting the mod, and deleting everything(Tracks, config AND mod), that last one works to fix it, for a little while anyway.

It's so bad, it spends more time skipping tracks then playing them, and sometimes it skips halfway through the playing track.

It's so bad I don't even use the mod anymore, I just put up with YouTube's ads and page reloading, because that's STILL more reliable

If this is an INTENDED feature, make it toggleable because this is driving me crazy, if it isn't intended, then please fix it. Thanks

### Log files and Screenshots

There are no logs, crashlogs, or screenshots, as it's hard to screenshot tracks skipping

### Used minecraft version

1.12.x

### Used forge or fabric version

Forge, Fabric, NeoForge, all of them

### Used mod version

I don't know the mod version, as it's not version specific

**Comment by HyCraftHD** [comment]
Hello, this seems to be a bug caused a playback error.
Can you upload the log please?

**Comment by VulDovahkiin** [comment]
I don't know if there IS a log, or where to find it for that matter. I've narrowed it down to ONLY affecting YouTube based tracks

**Comment by VulDovahkiin** [comment]
I have now found out that, out of 108 tracks from YouTube, only ONE of them plays somewhat consistently. And like I've said on my original post, this happens on all versions, from the first 1.8 releases, to the latest ones. The game isn't crashing, there are no errors that I can find. Other than it skipping tracks from YouTube automatically, there are no bugs, issues, error logs, nothing.

**Comment by Old-World-Vulture** [comment]
I have been having this issue too, across both 1.12.2 and 1.20.1. I personally have looked through my general logs looking for any errors, but there is nothing there to indicate that anything is going wrong, there are no errors that I have found. All I have for evidence is this 5 second video showing the skipping. Hope it helps, I apologize if it doesn't.



https://github.com/user-attachments/assets/a12cf97f-b58a-4cac-97d0-2cc417580d34

**Comment by HyCraftHD** [comment]
It's probably the "Sign in Error".
Youtube has started to partially prevent the playback of videos outside the site without login. I'll see how I can make sense of this. Unfortunately, I will probably have to introduce that you have to log in to play YouTube.

**Comment by HyCraftHD** [comment]
A note about the logs: You probably didn't look at the debug log (or it was disabled by some stupid launcher settings). There should be enough stuff in the debug log to better diagnose the cause. However, I think it will also be the sign in error.

**Comment by HyCraftHD** [comment]
```java
[34m[15:44:32][m [33m[lava-daemon-pool-playback-1-thread-1/WARN][m [36m(LocalAudioTrackExecutor)[m [0mSuspicious exception for playback of xyz
[m com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:102) ~[?:?]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109) ~[?:?]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

	```

**Comment by SpyRuby** [comment]
um im having the same problem but im already signed it to youtube what do i do NOW?!

**Comment by SpyRuby** [comment]
> ```java
> �[34m[15:44:32]�[m �[33m[lava-daemon-pool-playback-1-thread-1/WARN]�[m �[36m(LocalAudioTrackExecutor)�[m �[0mSuspicious exception for playback of xyz
> �[m com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
> 	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:102) ~[?:?]
> 	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109) ~[?:?]
> 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339) ~[?:?]
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
> 	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
> 
> 	```
> ```

um what is this?

**Comment by SpyRuby** [comment]
> I have now found out that, out of 108 tracks from YouTube, only ONE of them plays somewhat consistently. And like I've said on my original post, this happens on all versions, from the first 1.8 releases, to the latest ones. The game isn't crashing, there are no errors that I can find. Other than it skipping tracks from YouTube automatically, there are no bugs, issues, error logs, nothing.

same thing i can play only one of them and no other ones

**Comment by SpyRuby** [comment]
> It's probably the "Sign in Error". Youtube has started to partially prevent the playback of videos outside the site without login. I'll see how I can make sense of this. Unfortunately, I will probably have to introduce that you have to log in to play YouTube.
same problem but im ALREADY SIGNED IN!!!!!!!!!!

**Comment by solarchx** [comment]
will there be eta on a fix?

**Comment by HyCraftHD** [comment]
Should be fixed with the latest updates
