### ISSUE TITLE
[1.12.2-1.14.4] Wrong import

### ISSUE THREAD

**Issue by HyCraftHD** [MC-U-Team/Music-Player#19]
Instead of the normal InputStreamReader from the jdk we use some weird stuff from an other library which seems to work but is still not desirable. Also there was a bugreport where it crashes because of the library missing on the buildpath. So change that to the normal InputStreamReader.

https://github.com/MC-U-Team/Music-Player/blob/1.14.4/src/main/java/info/u_team/music_player/musicplayer/PlaylistManager.java#L8

**Comment by HyCraftHD** [comment]
Fixes crash when jline is not in the classpath. (Should not happen because that library is shipped with minecraft / forge but people reported issues)

**Comment by Cam284** [comment]
its still no work
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreModLoader (Sound-Physics-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 8/15/19 10:21 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Music Player (musicplayer)
Caused by: java.lang.NoClassDefFoundError: org/jline/utils/InputStreamReader
	at info.u_team.music_player.musicplayer.MusicPlayerManager.<clinit>(MusicPlayerManager.java:19)
	at info.u_team.music_player.proxy.ClientProxy.init(ClientProxy.java:27)
	at info.u_team.music_player.MusicPlayerMod.init(MusicPlayerMod.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:720)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: org.jline.utils.InputStreamReader
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 43 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 45 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 862516600 bytes (822 MB) / 1845493760 bytes (1760 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version             | Source                             | Signature                                |
	|:----- |:----------------- |:------------------- |:---------------------------------- |:---------------------------------------- |
	| UCHI  | minecraft         | 1.12.2              | minecraft.jar                      | None                                     |
	| UCHI  | mcp               | 9.42                | minecraft.jar                      | None                                     |
	| UCHI  | FML               | 8.0.99.99           | forge-1.12.2-14.23.2.2611.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | forge             | 14.23.2.2611        | forge-1.12.2-14.23.2.2611.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | mercurius_updater | 1.0                 | MercuriusUpdater-1.12.2.jar        | None                                     |
	| UCHI  | extendedrenderer  | v1.0                | coroutil-1.12.1-1.2.32.jar         | None                                     |
	| UCHI  | coroutil          | 1.12.1-1.2.32       | coroutil-1.12.1-1.2.32.jar         | None                                     |
	| UCHI  | configmod         | v1.0                | coroutil-1.12.1-1.2.32.jar         | None                                     |
	| UCHI  | grapplemod        | 1.12.2-v11.1        | grapplemod-v11.1-1.12.2.jar        | None                                     |
	| UCHI  | lostcities        | 2.0.21              | lostcities-1.12-2.0.21.jar         | None                                     |
	| UCHI  | lycanitesmobs     | 2.0.0.4 - MC 1.12.2 | lycanitesmobs-1.12.2-2.0.0.4.jar   | None                                     |
	| UCHI  | uteamcore         | 2.2.4.107           | u_team_core-1.12.2-2.2.4.107.jar   | None                                     |
	| UCHE  | musicplayer       | 2.0.2.25            | music_player-1.12.2-2.0.2.25.jar   | None                                     |
	| UCHI  | soundphysics      | 1.0.8               | Sound-Physics-1.12.2.jar           | None                                     |
	| UCHI  | zombieawareness   | 1.12.1-1.11.16      | zombieawareness-1.12.1-1.11.16.jar | None                                     |

	Loaded coremods (and transformers): 
CoreModLoader (Sound-Physics-1.12.2.jar)
  com.sonicether.soundphysics.CoreModInjector
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GTX 750/PCIe/SSE2'

**Comment by HyCraftHD** [comment]
You have not updated the music player version. The "fixed" 1.12.2 version is: 1.12.2-2.0.3.31

**Comment by Cam284** [comment]
Well give me the link to it

**Comment by HyCraftHD** [comment]
Its the latest download on the curseforge page..
https://www.curseforge.com/minecraft/mc-mods/music-player/files/2762374
