### ISSUE TITLE
crashing when trying to input control key / opening the menu

### ISSUE THREAD

**Issue by XANADIUMMOXXY** [MC-U-Team/Music-Player#21]
When I try to input the key / opening the menu, the game crashes. I'm using mod version 2.0.0 with the required mod and others. 

![bruh](https://user-images.githubusercontent.com/55020163/64474082-7aaefa80-d199-11e9-9bcf-fe25ae7f3d0c.gif)

And here's the mods i used in MC

![cf46b4e037cedad6f197f6ed69897e75](https://user-images.githubusercontent.com/55020163/64474124-41c35580-d19a-11e9-974c-2185de172907.png)

**Comment by HyCraftHD** [comment]
Hello,
Thanks for the report! Can you please send the the crashreport?

**Comment by XANADIUMMOXXY** [comment]
here's the latest crash report.

[crash-2019-09-07_18.06.19-client.txt](https://github.com/MC-U-Team/Music-Player/files/3586542/crash-2019-09-07_18.06.19-client.txt)

**Comment by HyCraftHD** [comment]
Thanks.
Seems like the playlist file is broken and could not be loaded. Can you also send me the log (debug.log)?
To fix this problem you should delete the playlist file: `%appdata%\mc-u-team\musicplayer\playlist.json.gz`. Have you every created playlists before?

**Comment by XANADIUMMOXXY** [comment]
Thank you, at one point while i'm trying to creating a playlist my room went blackout, guess that caused the the playlist corrupted. Also here's the log

[debug.log](https://github.com/MC-U-Team/Music-Player/files/3586548/debug.log)

**Comment by HyCraftHD** [comment]
Thanks again.
This seemed to be the cause. The playlist file is corrupted, just delete it and it should work again.

I think I should autodelete the corrupted files or switch to a non zip based file format.

~Johannes

``` java
[18:04:31] [Client thread/ERROR] [info.u_team.music_player.musicplayer.PlaylistManager]: Could not ready playlist file at C:\Users\XANADIUM\AppData\Roaming\mc-u-team\musicplayer\playlist.json.gz
java.util.zip.ZipException: Not in GZIP format
	at java.util.zip.GZIPInputStream.readHeader(Unknown Source) ~[?:1.8.0_192]
	at java.util.zip.GZIPInputStream.<init>(Unknown Source) ~[?:1.8.0_192]
	at java.util.zip.GZIPInputStream.<init>(Unknown Source) ~[?:1.8.0_192]
	at info.u_team.music_player.musicplayer.PlaylistManager.loadFromFile(PlaylistManager.java:36) [PlaylistManager.class:2.0.3.31]
	at info.u_team.music_player.musicplayer.MusicPlayerManager.setup(MusicPlayerManager.java:25) [MusicPlayerManager.class:2.0.3.31]
	at info.u_team.music_player.proxy.ClientProxy.init(ClientProxy.java:27) [ClientProxy.class:2.0.3.31]
	at info.u_team.music_player.MusicPlayerMod.init(MusicPlayerMod.java:28) [MusicPlayerMod.class:2.0.3.31]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_192]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_192]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_192]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_192]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```
