### ISSUE TITLE
[1.15.2] Crash with skip

### ISSUE THREAD

**Issue by HyCraftHD** [MC-U-Team/Music-Player#35]
**Describe the bug**
Crash on skip

**To Reproduce**
1. Invalid song (e.g. remove mp3 file from folder, but don't remove it from the playlist
2. Load playlist and start playing
3. Shuffle mode is enabled
4. Skip and the game will crash

**Expected behavior**
Should not crash

**Screenshots**

**Versions**
- Mod Version: All
- Minecraft Version: All
- Forge Version: All
- UTeamCore Version: All

**Log (if crash occures)**
https://pastebin.com/XQ2c34gL

**Comment by HyCraftHD** [comment]
Same happens when a song ends with shuffle mode enabled. Log is as follows:

```java
[Audio Player] ERROR com.sedmelluq.discord.lavaplayer.player.AudioPlayer - Handler of event com.sedmelluq.discord.lavaplayer.player.event.TrackEndEvent@3c97c9ff threw an exception.
[m[32m[01:32:16] [Audio Player/INFO] [STDERR/]: [org.slf4j.impl.SimpleLogger:write:319]: java.lang.NullPointerException
[m[32m[01:32:16] [Audio Player/INFO] [STDERR/]: [org.slf4j.impl.SimpleLogger:write:319]: 	at info.u_team.music_player.musicplayer.playlist.Playlist.lambda$4(Playlist.java:306)
[m[32m[01:32:16] [Audio Player/INFO] [STDERR/]: [org.slf4j.impl.SimpleLogger:write:319]: 	at java.util.ArrayList.forEach(ArrayList.java:1257)
[m[32m[01:32:16] [Audio Player/INFO] [STDERR/]: [org.slf4j.impl.SimpleLogger:write:319]: 	at info.u_team.music_player.musicplayer.playlist.Playlist.calculateNext(Playlist.java:302)
[m[32m[01:32:16] [Audio Player/INFO] [STDERR/]: [org.slf4j.impl.SimpleLogger:write:319]: 	at info.u_team.music_player.lavaplayer.queue.TrackQueueWrapper.calculateNext(TrackQueueWrapper.java:18)
[m[32m[01:32:16] [Audio Player/INFO] [STDERR/]: [org.slf4j.impl.SimpleLogger:write:319]: 	at info.u_team.music_player.lavaplayer.queue.TrackManager.skip(TrackManager.java:56)
[m[32m[01:32:16] [Audio Player/INFO] [STDERR/]: [org.slf4j.impl.SimpleLogger:write:319]: 	at info.u_team.music_player.lavaplayer.queue.TrackManager.onTrackEnd(TrackManager.java:25)
[m[32m[01:32:16] [Audio Player/INFO] [STDERR/]: [org.slf4j.impl.SimpleLogger:write:319]: 	at com.sedmelluq.discord.lavaplayer.player.event.AudioEventAdapter.onEvent(AudioEventAdapter.java:70)
[m[32m[01:32:16] [Audio Player/INFO] [STDERR/]: [org.slf4j.impl.SimpleLogger:write:319]: 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer.dispatchEvent(DefaultAudioPlayer.java:350)
[m[32m[01:32:16] [Audio Player/INFO] [STDERR/]: [org.slf4j.impl.SimpleLogger:write:319]: 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer.handleTerminator(DefaultAudioPlayer.java:260)
[m[32m[01:32:16] [Audio Player/INFO] [STDERR/]: [org.slf4j.impl.SimpleLogger:write:319]: 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer.provide(DefaultAudioPlayer.java:196)
[m[32m[01:32:16] [Audio Player/INFO] [STDERR/]: [org.slf4j.impl.SimpleLogger:write:319]: 	at com.sedmelluq.discord.lavaplayer.format.AudioPlayerInputStream.attemptRetrieveFrame(AudioPlayerInputStream.java:110)
[m[32m[01:32:16] [Audio Player/INFO] [STDERR/]: [org.slf4j.impl.SimpleLogger:write:319]: 	at com.sedmelluq.discord.lavaplayer.format.AudioPlayerInputStream.ensureAvailable(AudioPlayerInputStream.java:94)
[m[32m[01:32:16] [Audio Player/INFO] [STDERR/]: [org.slf4j.impl.SimpleLogger:write:319]: 	at com.sedmelluq.discord.lavaplayer.format.AudioPlayerInputStream.read(AudioPlayerInputStream.java:56)
[m[32m[01:32:16] [Audio Player/INFO] [STDERR/]: [org.slf4j.impl.SimpleLogger:write:319]: 	at javax.sound.sampled.AudioInputStream.read(AudioInputStream.java:292)
[m[32m[01:32:16] [Audio Player/INFO] [STDERR/]: [org.slf4j.impl.SimpleLogger:write:319]: 	at javax.sound.sampled.AudioInputStream.read(AudioInputStream.java:232)
[m[32m[01:32:16] [Audio Player/INFO] [STDERR/]: [org.slf4j.impl.SimpleLogger:write:319]: 	at info.u_team.music_player.lavaplayer.output.AudioOutput.run(AudioOutput.java:56)
```
