### ISSUE TITLE
[1.18.2] Nothing plays and it just skips to the next track repeatedly

### ISSUE THREAD

**Issue by Nulled-Pointer** [MC-U-Team/Music-Player#421]
### Bug description and reproduction steps

When trying to play from any playlist, nothing plays and it skips to the next track in the playlist. This continues to happen until it reaches a normal end condition (such as the end of the playlist if it is not set to loop). This was working before and randomly stopped working for no logical reason

### Log files and Screenshots

[latest.log](https://github.com/MC-U-Team/Music-Player/files/9315651/latest.log)
Error seems to be at line 2579
[11:28:40] [pool-24-thread-1/ERROR]: Uncaught exception in thread "pool-24-thread-1"
java.lang.NullPointerException: Cannot read field "field_1755" because "this.field_22787" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4) ~[?:?]
	at info.u_team.music_player.gui.playlist.GuiMusicPlaylist.lambda$new$1(GuiMusicPlaylist.java:34) ~[music_player-fabric-1.18.2-2.3.4.4.jar:?]
	at info.u_team.music_player.musicplayer.playlist.Playlist.lambda$load$3(Playlist.java:89) ~[music_player-fabric-1.18.2-2.3.4.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

### Used minecraft version

1.18.x

### Used forge version

Fabric 0.14.9

### Used mod version

2.3.4.4

**Comment by HyCraftHD** [comment]
Working on a fix. Youtube changed something. Related to #420

**Comment by Nulled-Pointer** [comment]
cool, thx

**Comment by HyCraftHD** [comment]
Fixed in these versions: 
![image](https://user-images.githubusercontent.com/7681220/184344677-d7f0cd33-1311-4ebb-acb1-cea89a49bde5.png)
