### ISSUE TITLE
[1.19] YouTube links do not seem to work anymore ("Loading information for a YouTube track failed")

### ISSUE THREAD

**Issue by KajeArch** [MC-U-Team/Music-Player#483]
### Bug description and reproduction steps

While all other sources seem to work, YouTube doesn't. As soon as I press play, it quickly iterates through all YouTube links, ultimately turning them red and saying: "Loading information for a YouTube track failed". I have tried deleting and reinstalling the mod and it didn't help. I believe YouTube might have changed something in their API

### Log files and Screenshots

![grafik](https://user-images.githubusercontent.com/50534112/194726696-4b2dd168-68bb-4248-8d85-056d16d14993.png)
logs:
[22:26:33] [lava-daemon-pool-info-loader-2-thread-2/INFO]: [STDERR]: Caused by: java.lang.IllegalStateException: No match found
[22:26:33] [lava-daemon-pool-info-loader-2-thread-2/INFO]: [STDERR]: 	at java.base/java.util.regex.Matcher.group(Matcher.java:644)
[22:26:33] [lava-daemon-pool-info-loader-2-thread-2/INFO]: [STDERR]: 	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.extractFromScript(YoutubeSignatureCipherManager.java:250)
[22:26:33] [lava-daemon-pool-info-loader-2-thread-2/INFO]: [STDERR]: 	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getExtractedScript(YoutubeSignatureCipherManager.java:165)
[22:26:33] [lava-daemon-pool-info-loader-2-thread-2/INFO]: [STDERR]: 	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackInfoFromInnertube(DefaultYoutubeTrackDetailsLoader.java:207)
[22:26:33] [lava-daemon-pool-info-loader-2-thread-2/INFO]: [STDERR]: 	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:56)
[22:26:33] [lava-daemon-pool-info-loader-2-thread-2/INFO]: [STDERR]: 	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:44)
[22:26:33] [lava-daemon-pool-info-loader-2-thread-2/INFO]: [STDERR]: 	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:228)
[22:26:33] [lava-daemon-pool-info-loader-2-thread-2/INFO]: [STDERR]: 	... 14 more

### Used minecraft version

1.19.x

### Used forge version

fabric-api-0.58.0+1.19 

### Used mod version

Music-Player (Fabric)-1.19.2-2.4.1.11

**Comment by HyCraftHD** [comment]
The versions of the mod and fabric do not match.
It seems you probably did not update to 1.19.2 where this bug was fixed.

**Comment by KajeArch** [comment]
> The versions of the mod and fabric do not match. It seems you probably did not update to 1.19.2 where this bug was fixed.

Oh yeah, that was a mistake of mine. I did not update to 1.19.2 yet, for very good reasons. I currently use 1.19 and the corresponding Music Player for 1.19. Minecraft 1.19 also still seems to be in use by a majority of users as of now. What exactly has changed in the newer version of Music Player? If it's not too much, I don't think it should be much of a problem to update it for 1.19 as well so YouTube links work again. @HyCraftHD

**Comment by HyCraftHD** [comment]
Well, I am not a fan of this debate.
I'll update one last time to make it work, but then that's it.
