### ISSUE TITLE
[1.12.2] slf4j error

### ISSUE THREAD

**Issue by sroldk** [MC-U-Team/Music-Player#49]
Error when i launched minecraft

`java.lang.IncompatibleClassChangeError: Class org.slf4j.impl.SimpleLoggerFactory does not implement the requested interface org.b.a
    at org.b.c.a(Unknown Source)
    at org.b.c.a(Unknown Source)
    at com.brsanthu.googleanalytics.discovery.DefaultRequestParameterDiscoverer.<clinit>(Unknown Source)
    at com.brsanthu.googleanalytics.GoogleAnalyticsConfig.<init>(Unknown Source)
    at com.brsanthu.googleanalytics.GoogleAnalyticsBuilder.<init>(Unknown Source)
    at com.brsanthu.googleanalytics.GoogleAnalytics.builder(Unknown Source)
    at io.github.ImpactDevelopment.installer.utils.Tracky.analytics(Unknown Source)
    at io.github.ImpactDevelopment.installer.utils.Tracky.<clinit>(Unknown Source)
    at net.impactclient.0GX.2(0GX.java:99)
    at net.impactclient.5.0(5.java:6)
    at net.minecraft.client.Minecraft.handler$init$zda000(Minecraft.java:4850)
    at net.minecraft.client.Minecraft.init(Minecraft.java:570)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
`

**Comment by HyCraftHD** [comment]
This issue is not caused by this mod.
Seems like the cheat client does that.
It could be a compatibily issue with the slf4j simple implementation, but not sure as this mod is obfuscated.
Also the issue template is there for a reason. I need the versions you are using to help you.

**Comment by sroldk** [comment]
I delete Impact and its working
