### ISSUE TITLE
incompatible mod set

### ISSUE THREAD

**Issue by antoine33doucet** [MC-U-Team/Music-Player#585]
hi, 
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, version 0.72.0+1.19.3 or later.
Unmet dependency listing:
	 - Mod 'Music Player' (musicplayer) 2.5.0.15 requires version 0.72.0+1.19.3 or later of fabric, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	
but yet I am using the correct version of fabric

**Comment by HyCraftHD** [comment]
You need to install the fabric api 0.72.0+1.19.3 or higher
