### ISSUE TITLE
[1.8.9] Mod can't download music from Youtube after some time of activity

### ISSUE THREAD

**Issue by Fl414r** [MC-U-Team/Music-Player#820]
### Bug description and reproduction steps

1. Start Minecraft
2. Just play and listen online (at least youtube, because can't check SoundCloud) music
3. Music stops playing, only offline works
It works fine for a while, but then this error occurs

### Log files and Screenshots

Video showing the bug itself
https://github.com/MC-U-Team/Music-Player/assets/74704475/b9772d95-c7ee-48dc-8f91-a9ebe6bf5335 (3.9mb)

Error while trying play Youtube music

[18:23:39] [lava-daemon-pool-playback-1-thread-18/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:write:341]: [lava-daemon-pool-playback-1-thread-18] ERROR com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor - Error in playback of dQw4w9WgXcQ
[18:23:39] [lava-daemon-pool-playback-1-thread-18/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:write:342]: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
[18:23:39] [lava-daemon-pool-playback-1-thread-18/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:write:342]: 	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44)
[18:23:39] [lava-daemon-pool-playback-1-thread-18/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:write:342]: 	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116)
[18:23:39] [lava-daemon-pool-playback-1-thread-18/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:write:342]: 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:361)
[18:23:39] [lava-daemon-pool-playback-1-thread-18/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:write:342]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[18:23:39] [lava-daemon-pool-playback-1-thread-18/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:write:342]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[18:23:39] [lava-daemon-pool-playback-1-thread-18/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:write:342]: 	at java.lang.Thread.run(Unknown Source)
[18:23:39] [lava-daemon-pool-playback-1-thread-18/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:writeThrowable:349]: 	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.4.2-original
  os.arch: amd64
  os.name: Windows 10
  os.version: 10.0
  java.vendor: Oracle Corporation
  java.version: 1.8.0_371
  java.runtime.version: 1.8.0_371-b11
  java.vm.version: 25.371-b11
[18:23:39] [lava-daemon-pool-playback-1-thread-18/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:writeThrowable:349]: Caused by: java.lang.RuntimeException: Not success status code: 403
[18:23:39] [lava-daemon-pool-playback-1-thread-18/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:writeThrowable:349]: 	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:87)
[18:23:39] [lava-daemon-pool-playback-1-thread-18/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:writeThrowable:349]: 	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:123)
[18:23:39] [lava-daemon-pool-playback-1-thread-18/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:writeThrowable:349]: 	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:105)
[18:23:39] [lava-daemon-pool-playback-1-thread-18/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:writeThrowable:349]: 	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:157)
[18:23:39] [lava-daemon-pool-playback-1-thread-18/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:writeThrowable:349]: 	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:173)
[18:23:39] [lava-daemon-pool-playback-1-thread-18/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:writeThrowable:349]: 	at java.io.DataInputStream.readByte(Unknown Source)
[18:23:39] [lava-daemon-pool-playback-1-thread-18/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:writeThrowable:349]: 	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39)
[18:23:39] [lava-daemon-pool-playback-1-thread-18/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:writeThrowable:349]: 	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:45)
[18:23:39] [lava-daemon-pool-playback-1-thread-18/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:writeThrowable:349]: 	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:78)
[18:23:39] [lava-daemon-pool-playback-1-thread-18/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:writeThrowable:349]: 	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:51)
[18:23:39] [lava-daemon-pool-playback-1-thread-18/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:writeThrowable:349]: 	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:34)
[18:23:39] [lava-daemon-pool-playback-1-thread-18/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:writeThrowable:349]: 	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
[18:23:39] [lava-daemon-pool-playback-1-thread-18/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:writeThrowable:349]: 	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:58)
[18:23:39] [lava-daemon-pool-playback-1-thread-18/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:writeThrowable:349]: 	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:50)
[18:23:39] [lava-daemon-pool-playback-1-thread-18/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:writeThrowable:349]: 	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)
[18:23:39] [lava-daemon-pool-playback-1-thread-18/INFO] [STDERR]: [org.slf4j.impl.SimpleLogger:writeThrowable:349]: 	... 4 more

------------------------------------
Log (a LOT of spam by Hypixel Skyblock mods)

[fml-client-latest.log](https://github.com/MC-U-Team/Music-Player/files/12314585/fml-client-latest.log) (7.7mb)

### Used minecraft version

1.8.x

### Used forge or fabric version

11.15.1.2318

### Used mod version

2.1.1.218

**Comment by Catomax262** [comment]
Why hasn't HyCraft done anything about this?

**Comment by HyCraftHD** [comment]
Thanks for the report, will be fixed soon with an update to lavaplayer as youtube changed some internal stuff again.

**Comment by HyCraftHD** [comment]
Should be fixed in these versions: 
![image](https://github.com/MC-U-Team/Music-Player/assets/7681220/f304e7c5-db76-4741-a308-d13c5c67194f)
