### ISSUE TITLE
[Fabric 1.20.1] Can't read (95%) local songs

### ISSUE THREAD

**Issue by Fl414r** [MC-U-Team/Music-Player#842]
### Bug description and reproduction steps

Another day, another bug

1) start MC
2) download some songs to local storage and try adding them to a playlist
3) ~95% of songs return "Unknown file format" error

All this songs 100% works, because I listened it on older versions (and even Windows Media Player can open it)

### Log files and Screenshots

[00:07:26] [lava-daemon-pool-info-loader-2-thread-36/INFO]: [STDERR]: [lava-daemon-pool-info-loader-2-thread-36] WARN com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection - Attempting to detect file with container mp3 failed.
[00:07:26] [lava-daemon-pool-info-loader-2-thread-36/INFO]: [STDERR]: java.lang.IndexOutOfBoundsException: Range [4, 4 + 1040) out of bounds for length 961
[00:07:26] [lava-daemon-pool-info-loader-2-thread-36/INFO]: [STDERR]: 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[00:07:26] [lava-daemon-pool-info-loader-2-thread-36/INFO]: [STDERR]: 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromIndexSize(Preconditions.java:82)
[00:07:26] [lava-daemon-pool-info-loader-2-thread-36/INFO]: [STDERR]: 	at java.base/jdk.internal.util.Preconditions.checkFromIndexSize(Preconditions.java:361)
[00:07:26] [lava-daemon-pool-info-loader-2-thread-36/INFO]: [STDERR]: 	at java.base/java.util.Objects.checkFromIndexSize(Objects.java:411)
[00:07:26] [lava-daemon-pool-info-loader-2-thread-36/INFO]: [STDERR]: 	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:198)
[00:07:26] [lava-daemon-pool-info-loader-2-thread-36/INFO]: [STDERR]: 	at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3FrameReader.fillFrameBuffer(Mp3FrameReader.java:121)
[00:07:26] [lava-daemon-pool-info-loader-2-thread-36/INFO]: [STDERR]: 	at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3TrackProvider.initialiseSeeker(Mp3TrackProvider.java:92)
[00:07:26] [lava-daemon-pool-info-loader-2-thread-36/INFO]: [STDERR]: 	at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3TrackProvider.parseHeaders(Mp3TrackProvider.java:87)
[00:07:26] [lava-daemon-pool-info-loader-2-thread-36/INFO]: [STDERR]: 	at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3ContainerProbe.probe(Mp3ContainerProbe.java:57)
[00:07:26] [lava-daemon-pool-info-loader-2-thread-36/INFO]: [STDERR]: 	at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.checkContainer(MediaContainerDetection.java:92)
[00:07:26] [lava-daemon-pool-info-loader-2-thread-36/INFO]: [STDERR]: 	at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.detectContainer(MediaContainerDetection.java:77)
[00:07:26] [lava-daemon-pool-info-loader-2-thread-36/INFO]: [STDERR]: 	at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.detectContainer(MediaContainerDetection.java:59)
[00:07:26] [lava-daemon-pool-info-loader-2-thread-36/INFO]: [STDERR]: 	at com.sedmelluq.discord.lavaplayer.source.local.LocalAudioSourceManager.detectContainerForFile(LocalAudioSourceManager.java:58)
[00:07:26] [lava-daemon-pool-info-loader-2-thread-36/INFO]: [STDERR]: 	at com.sedmelluq.discord.lavaplayer.source.local.LocalAudioSourceManager.loadItem(LocalAudioSourceManager.java:41)
[00:07:26] [lava-daemon-pool-info-loader-2-thread-36/INFO]: [STDERR]: 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:412)
[00:07:26] [lava-daemon-pool-info-loader-2-thread-36/INFO]: [STDERR]: 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:394)
[00:07:26] [lava-daemon-pool-info-loader-2-thread-36/INFO]: [STDERR]: 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.loadItemSync(DefaultAudioPlayerManager.java:156)
[00:07:26] [lava-daemon-pool-info-loader-2-thread-36/INFO]: [STDERR]: 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$loadItem$0(DefaultAudioPlayerManager.java:175)
[00:07:26] [lava-daemon-pool-info-loader-2-thread-36/INFO]: [STDERR]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[00:07:26] [lava-daemon-pool-info-loader-2-thread-36/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[00:07:26] [lava-daemon-pool-info-loader-2-thread-36/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[00:07:26] [lava-daemon-pool-info-loader-2-thread-36/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833) 

![Снимок экрана (94)](https://github.com/MC-U-Team/Music-Player/assets/74704475/56db4dfd-35cd-447f-925c-785a44b5be5f)

### Used minecraft version

1.20.x

### Used forge or fabric version

fabric 0.14.22

### Used mod version

2.7.0.235

**Comment by Fl414r** [comment]
Some songs still can be played
![Снимок экрана (95)](https://github.com/MC-U-Team/Music-Player/assets/74704475/52c40804-7c4f-46d3-9619-79eb23f630ff)
